# Generated by Django 5.2 on 2025-04-13 13:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at'], 'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирования'},
        ),
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-created_at'], 'verbose_name': 'Жалоба', 'verbose_name_plural': 'Жалобы'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-date', '-time'], 'verbose_name': 'Поездка', 'verbose_name_plural': 'Поездки'},
        ),
        migrations.AlterModelOptions(
            name='tripreport',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отчет', 'verbose_name_plural': 'Отчеты'},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='trip',
            name='departure_address',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='departure_city',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='destination_address',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='destination_city',
        ),
        migrations.RemoveField(
            model_name='tripreport',
            name='average_trip_price',
        ),
        migrations.RemoveField(
            model_name='tripreport',
            name='total_distance',
        ),
        migrations.AddField(
            model_name='trip',
            name='departure_location',
            field=models.CharField(default=2, max_length=255, verbose_name='Место отправления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='destination_location',
            field=models.CharField(default=2, max_length=255, verbose_name='Место назначения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Пассажир'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_note',
            field=models.TextField(blank=True, verbose_name='Примечание к оплате'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seats_booked',
            field=models.PositiveIntegerField(default=1, verbose_name='Забронировано мест'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено'), ('completed', 'Завершено'), ('paid', 'Оплачено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='rideshare_app.trip', verbose_name='Поездка'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='admin_notes',
            field=models.TextField(blank=True, verbose_name='Заметки администратора'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_type',
            field=models.CharField(choices=[('behavior', 'Поведение'), ('safety', 'Безопасность'), ('payment', 'Оплата'), ('other', 'Другое')], max_length=20, verbose_name='Тип жалобы'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='reported_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints_received', to=settings.AUTH_USER_MODEL, verbose_name='Обжалуемый пользователь'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints_filed', to=settings.AUTH_USER_MODEL, verbose_name='Заявитель'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', 'На рассмотрении'), ('investigating', 'Расследуется'), ('resolved', 'Решено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='rideshare_app.trip', verbose_name='Поездка'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель'),
        ),
        migrations.AlterField(
            model_name='message',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='rideshare_app.trip', verbose_name='Поездка'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking', 'Бронирование'), ('trip_update', 'Обновление поездки'), ('message', 'Сообщение'), ('review', 'Отзыв'), ('complaint', 'Жалоба'), ('payment', 'Оплата')], max_length=20, verbose_name='Тип уведомления'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewed_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL, verbose_name='Получатель отзыва'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL, verbose_name='Автор отзыва'),
        ),
        migrations.AlterField(
            model_name='review',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='rideshare_app.trip', verbose_name='Поездка'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='available_seats',
            field=models.PositiveIntegerField(verbose_name='Свободные места'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='departure_coords',
            field=models.CharField(max_length=50, verbose_name='Координаты отправления'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination_coords',
            field=models.CharField(max_length=50, verbose_name='Координаты назначения'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL, verbose_name='Водитель'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='route_distance',
            field=models.CharField(blank=True, max_length=50, verbose_name='Расстояние'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='route_duration',
            field=models.CharField(blank=True, max_length=50, verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='route_polyline',
            field=models.TextField(blank=True, verbose_name='Маршрут на карте'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активная'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='tripreport',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Средний рейтинг'),
        ),
        migrations.AlterField(
            model_name='tripreport',
            name='cancelled_trips',
            field=models.IntegerField(default=0, verbose_name='Отмененных поездок'),
        ),
        migrations.AlterField(
            model_name='tripreport',
            name='completed_trips',
            field=models.IntegerField(default=0, verbose_name='Завершенных поездок'),
        ),
        migrations.AlterField(
            model_name='tripreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='tripreport',
            name='end_date',
            field=models.DateField(verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='tripreport',
            name='popular_routes',
            field=models.JSONField(default=dict, verbose_name='Популярные маршруты'),
        ),
        migrations.AlterField(
            model_name='tripreport',
            name='report_type',
            field=models.CharField(choices=[('user', 'Отчет пользователя'), ('trip', 'Отчет по поездкам'), ('financial', 'Финансовый отчет')], max_length=20, verbose_name='Тип отчета'),
        ),
        migrations.AlterField(
            model_name='tripreport',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='tripreport',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общий доход'),
        ),
        migrations.AlterField(
            model_name='tripreport',
            name='total_passengers',
            field=models.IntegerField(default=0, verbose_name='Всего пассажиров'),
        ),
        migrations.AlterField(
            model_name='tripreport',
            name='total_trips',
            field=models.IntegerField(default=0, verbose_name='Всего поездок'),
        ),
        migrations.AlterField(
            model_name='tripreport',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
