# Generated by Django 5.2 on 2025-04-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare_app', '0002_alter_booking_options_alter_complaint_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='route_distance',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='route_duration',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='route_polyline',
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активная'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='active', max_length=20, verbose_name='Статус'),
        ),
    ]
