# Generated by Django 5.2 on 2025-04-15 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare_app', '0003_remove_trip_route_distance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='admin_notes',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='complaint_type',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='reporter',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='complaint',
            name='admin_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий администратора'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='complainant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='filed_complaints', to=settings.AUTH_USER_MODEL, verbose_name='Заявитель'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата рассмотрения'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='description',
            field=models.TextField(verbose_name='Описание жалобы'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='reported_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints_against', to=settings.AUTH_USER_MODEL, verbose_name='Жалоба на пользователя'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', 'На рассмотрении'), ('resolved', 'Рассмотрено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
