# Generated by Django 5.2.2 on 2025-06-05 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rideshare_app", "0006_package"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="package",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Посылка",
                "verbose_name_plural": "Посылки",
            },
        ),
        migrations.AddField(
            model_name="package",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Цена",
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "В поиске водителя"),
                    ("assigned", "В пути"),
                    ("delivered", "Доставлено"),
                    ("cancelled", "Отменено"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="trip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="packages",
                to="rideshare_app.trip",
                verbose_name="Поездка",
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
        ),
        migrations.AlterField(
            model_name="package",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="package",
            name="date",
            field=models.DateField(verbose_name="Дата отправки"),
        ),
        migrations.AlterField(
            model_name="package",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="package",
            name="destination",
            field=models.CharField(max_length=100, verbose_name="Куда"),
        ),
        migrations.AlterField(
            model_name="package",
            name="origin",
            field=models.CharField(max_length=100, verbose_name="Откуда"),
        ),
        migrations.AlterField(
            model_name="package",
            name="recipient_name",
            field=models.CharField(max_length=100, verbose_name="Получатель"),
        ),
        migrations.AlterField(
            model_name="package",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_packages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Отправитель",
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="weight_kg",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Вес (кг)"
            ),
        ),
    ]
